version: '3.8'

services:
  web:
    build: .
    command: gunicorn ncbi_sed_standalone.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file: .env
    networks:
      - ncbi-sed-network
  crypto-api:
    build: .
    command: gunicorn cryptoapi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file: .env
    networks:
      - ncbi-sed-network

networks:
  ncbi-sed-network:
    driver: bridge
    external: true