services:
  web:
    build:
      context: ./ncbi_sed_standalone
      dockerfile: Dockerfile.prod
    command: gunicorn ncbi_sed_standalone.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file: .env.prod
    depends_on:
      - redis
      - db
    networks:
      - ncbi-sed-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"
    networks:
      - ncbi-sed-network

  crypto-api:
    build:
      context: ./cryptoapi
      dockerfile: Dockerfile.cryptoapi
    command: gunicorn cryptoapi.wsgi:application --bind 0.0.0.0:8000
    container_name: crypto-api
    expose:
      - 8000
    env_file: .env.prod
    networks:
      - ncbi-sed-network

  redis:
    image: "redis:7"
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - ncbi-sed-network

  celery:
    build:
      context: ./ncbi_sed_standalone
      dockerfile: Dockerfile.prod
    container_name: celery
    command: celery -A ncbi_sed_standalone worker --loglevel=info
    env_file: .env.prod
    depends_on:
      - redis
    networks:
      - ncbi-sed-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
      - crypto-api
    networks:
      - ncbi-sed-network
    ports:
      - "80:80"


volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  ncbi-sed-network:
    driver: bridge
    external: true