FROM python:3.13-slim

RUN mkdir -p /home/app

RUN addgroup --system app && adduser --system --group app

ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    python3-dev \
    wget \
    libssl-dev \
    libmagic1 \
    libccid \
    pcscd \
    libgtk2.0-0 \
    libpq-dev \
    curl \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

WORKDIR /tmp

COPY linux-amd64_deb.tgz /tmp/
RUN tar -xvf /tmp/linux-amd64_deb.tgz -C /tmp
RUN chown -R root:root /tmp/linux-amd64_deb

RUN cd /tmp/linux-amd64_deb/ && \
    dpkg -i lsb-cprocsp-base_5.0.13300-7_all.deb && \
    dpkg -i lsb-cprocsp-rdr-64_5.0.13300-7_amd64.deb && \
    dpkg -i lsb-cprocsp-kc1-64_5.0.13300-7_amd64.deb && \
    dpkg -i lsb-cprocsp-capilite-64_5.0.13300-7_amd64.deb && \
    dpkg -i lsb-cprocsp-ca-certs_5.0.13300-7_all.deb && \
    apt-get install -f -y && \
    rm -rf /tmp/linux-arm64_deb


WORKDIR $APP_HOME

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . $APP_HOME

RUN chown -R app:app $APP_HOME

USER app

CMD ["bash"]