FROM python:3.13-slim

RUN mkdir -p /home/app
RUN addgroup --system app && adduser --system --group app

ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    poppler-utils \
    python3-dev \
    libssl-dev \
    libmagic1 \
    libpq-dev \
    curl \
    git \
    netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
  && apt-get install wkhtmltopdf -y \
  && mv /usr/bin/wkhtmltopdf /usr/local/bin/.


COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./db.prod.sh .
RUN sed -i 's/\r$//g'  $APP_HOME/db.prod.sh
RUN chmod +x  $APP_HOME/db.prod.sh

COPY . $APP_HOME

RUN chown -R app:app $APP_HOME

RUN mkdir -p /home/app/web/media
RUN chown -R app:app /home/app/web/media

RUN mkdir -p /home/app/web/media/previews
RUN chown -R app:app /home/app/web/media/previews

USER app

ENTRYPOINT ["sh", "/home/app/web/db.prod.sh"]
