FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    python3-dev \
    libssl-dev \
    libmagic1 \
    libpq-dev \
    curl \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
  && apt-get install wkhtmltopdf -y \
  && mv /usr/bin/wkhtmltopdf /usr/local/bin/.

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .


CMD ["gunicorn", "ncbi_sed_standalone.wsgi:application", "--bind", "0.0.0.0:8000"]
